<a href="https://colab.research.google.com/github/zahrapramesti649-cell/heart-attack-risk-prediction/blob/main/notebooks/03_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Heart Attack Risk Prediction

### Data Cleaning & Preprocessing

### Objective

This notebook aims to prepare a clean and structured dataset for exploratory data analysis (EDA) and machine learning modeling. The focus is on handling data quality issues such as missing values, ensuring appropriate data formats, and validating the overall dataset structure.

The output of this stage is a cleaned dataset that is consistent, reliable, and ready for further analysis and model development.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/heart_attack_dataset.csv", sep=";")
df.head()

,patient_id,age,gender,chest_pain_type,resting_bp,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_angina,...,num_major_vessels,thalassemia,bmi,smoking_status,alcohol_consumption,physical_activity,family_history,diabetes,stress_level,heart_attack_risk
0,1,59,Male,Asymptomatic,105.0,154.0,0.0,ST-T Abnormality,186.0,1,...,1,Fixed Defect,23.5,Former,Heavy,Moderate,1,1,6.0,0
1,2,50,Male,Non-anginal Pain,102.0,180.0,0.0,Normal,183.0,0,...,0,Reversible Defect,19.3,NaN,Moderate,High,0,0,8.0,0
2,3,61,Male,Atypical Angina,117.0,213.0,1.0,Normal,161.0,0,...,1,Fixed Defect,30.5,Never,Moderate,Low,1,1,2.0,1
3,4,73,Female,Atypical Angina,121.0,208.0,1.0,Normal,150.0,0,...,0,Normal,28.6,Former,Moderate,Moderate,0,0,4.0,0
4,5,49,Male,Non-anginal Pain,106.0,157.0,0.0,Normal,185.0,0,...,0,Reversible Defect,21.4,Former,Moderate,Moderate,0,0,NaN,0

### Missing Values Overview

Before proceeding with data cleaning, a re-evaluation of missing values is conducted to better understand their distribution and extent across variables. This step is essential for determining the most appropriate handling strategy, such as imputation or removal, to ensure data quality for subsequent analysis and modeling.

In [3]:
missing_values = df.isnull().sum()
missing_values

patient_id               0
age                      0
gender                   0
chest_pain_type          0
resting_bp             280
cholesterol            398
fasting_blood_sugar    196
resting_ecg            199
max_heart_rate         279
exercise_angina          0
oldpeak                350
st_slope                 0
num_major_vessels        0
thalassemia              0
bmi                    330
smoking_status         505
alcohol_consumption    405
physical_activity      346
family_history           0
diabetes                 0
stress_level           268
heart_attack_risk        0
dtype: int64

In [4]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [5]:
cat_cols = df.select_dtypes(include=['object']).columns

df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [6]:
df.isnull().sum()

patient_id             0
age                    0
gender                 0
chest_pain_type        0
resting_bp             0
cholesterol            0
fasting_blood_sugar    0
resting_ecg            0
max_heart_rate         0
exercise_angina        0
oldpeak                0
st_slope               0
num_major_vessels      0
thalassemia            0
bmi                    0
smoking_status         0
alcohol_consumption    0
physical_activity      0
family_history         0
diabetes               0
stress_level           0
heart_attack_risk      0
dtype: int64

### Data Cleaning Result

After handling missing values, all variables in the dataset are now complete with no missing entries. The imputation strategy applied includes using the median for numerical variables and the mode for categorical variables, as these approaches are robust to data distribution and suitable for preserving the overall characteristics of the dataset.

With these adjustments, the dataset is now clean, consistent, and ready for Exploratory Data Analysis (EDA).